=== Hasnaoui-Youssef/trailer_vibes/resources/Schemas/RZONE.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--

  Copyright (c) 2020 ARM Limited. All rights reserved.

  SPDX-License-Identifier: Apache-2.0

  Licensed under the Apache License, Version 2.0 (the License); you may
  not use this file except in compliance with the License.
  You may obtain a copy of the License at

  www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an AS IS BASIS, WITHOUT
  WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.

  $Date:        14. April 2020
  $Revision:    0.3.1

  $Project: Schema File for CMSIS-Zone resource description file *.rzone
  Version History:

  0.0.1: Initial Version
  0.0.2: splitting resources and assignments into separate files
         - resources only
  0.1.0: adding security attribute for memory, peripheral and assign
  0.1.1: adding privilege attribute for memory, peripheral and assign tags
  0.2.0: adding sau_init, mpc, peripheral setup element for security and privilege control
  0.3.0: rename Pref to Pname, removed processor_group element, added peripheral childs interrupt, setup and slot elements
  0.3.1: added DnumMpuRegions to rzone/device/processor element with default value 8
-->

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="qualified" version="0.1.1">

  <!-- NonNegativeInteger specifies the format in which numbers are represented in hexadecimal or decimal format -->
  <xs:simpleType name="NonNegativeInteger">
    <xs:restriction base="xs:string">
      <xs:pattern value="[+]?(0x|0X)?[0-9a-fA-F]+" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="Integer">
    <xs:restriction base="xs:string">
      <xs:pattern value="[+\-]?(0x|0X)?[0-9a-fA-F]+" />
    </xs:restriction>
  </xs:simpleType>

  <!-- some strings are used to construct filenames (e.g. package name). Such names can contain only subset of characters
       and must not contain neither spaces nor dots.  -->
  <xs:simpleType name="RestrictedString">
    <xs:restriction base="xs:string">
      <xs:pattern value="[\-_A-Za-z0-9]+" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="SchemaVersionType">
    <xs:restriction base="xs:string">
      <xs:pattern value="[0-9]+\.[0-9]+((\.[0-9]+)|())" />
    </xs:restriction>
  </xs:simpleType>

  <!-- semantic versioning -->
  <xs:simpleType name="PackVersionType">
    <xs:restriction base="xs:string">
      <!-- major . minor . patch [[-]quality] [+build] -->
      <xs:pattern value="[0-9]+.[0-9]+.[0-9]+((\-[0-9A-Za-z_\-\.]+)|([_A-Za-z][0-9A-Za-z_\-\.]*)|())((\+[\-\._A-Za-z0-9]+)|())" />
    </xs:restriction>
  </xs:simpleType>

  <!-- CoreRevisionType specifies the CPU revision format as defined by ARM (rNpM) -->
  <xs:simpleType name="DcoreVersionType">
    <xs:restriction base="xs:string">
      <xs:pattern value="r[0-9]*p[0-9]*"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="InstancesType">
    <xs:restriction base="xs:unsignedInt">
      <xs:minInclusive value="1" />
    </xs:restriction>
  </xs:simpleType>

  <!-- Dcore enumeration type -->
  <xs:simpleType name="DcoreType">
    <xs:restriction base="xs:string">
      <xs:pattern value="SC[0-9][0-9][0-9]" />
      <xs:pattern value="Cortex\-[AMR][0-9][0-9]?[P]?" />
    </xs:restriction>
  </xs:simpleType>


  <!-- Dfpu enumeration type -->
  <xs:simpleType name="DfpuTypeEnum">
    <xs:restriction base="xs:token">
      <!-- core has FPU (type of FPU depends on Dcore) -->
      <xs:enumeration value="FPU" />
      <xs:enumeration value="1" />
      <!-- core has no FPU -->
      <xs:enumeration value="NO_FPU" />
      <xs:enumeration value="0" />
      <!-- single precision FPU -->
      <xs:enumeration value="SP_FPU" />
      <!-- double precision FPU -->
      <xs:enumeration value="DP_FPU" />
      <!-- any -->
    </xs:restriction>
  </xs:simpleType>

  <!-- Dmpu enumeration type -->
  <xs:simpleType name="DmpuTypeEnum">
    <xs:restriction base="xs:token">
      <xs:enumeration value="MPU" />
      <xs:enumeration value="NO_MPU" />
      <xs:enumeration value="0" />
      <xs:enumeration value="1" />
      <xs:enumeration value="*" />
    </xs:restriction>
  </xs:simpleType>

  <!-- Dtz TrustZone enumeration type -->
  <xs:simpleType name="DtzTypeEnum">
    <xs:restriction base="xs:token">
      <xs:enumeration value="TZ" />
      <xs:enumeration value="NO_TZ" />
      <xs:enumeration value="1" />
      <xs:enumeration value="0" />
      <xs:enumeration value="*" />
    </xs:restriction>
  </xs:simpleType>

  <!-- Dsecure enumeration type -->
  <xs:simpleType name="DsecureTypeEnum">
    <xs:restriction base="xs:token">
      <xs:enumeration value="Secure" />
      <xs:enumeration value="Non-secure" />
      <xs:enumeration value="1" />
      <xs:enumeration value="0"/>
      <xs:enumeration value="*" />
    </xs:restriction>
  </xs:simpleType>

  <!-- Ddsp DSP extensions enumeration type -->
  <xs:simpleType name="DdspTypeEnum">
    <xs:restriction base="xs:token">
      <xs:enumeration value="DSP" />
      <xs:enumeration value="NO_DSP" />
      <xs:enumeration value="1" />
      <xs:enumeration value="0" />
      <xs:enumeration value="*" />
    </xs:restriction>
  </xs:simpleType>

  <!-- Dendian enumeration type -->
  <xs:simpleType name="DendianTypeEnum">
    <xs:restriction base="xs:token">
      <xs:enumeration value="Little-endian" />
      <xs:enumeration value="Big-endian" />
      <xs:enumeration value="Configurable" />
      <xs:enumeration value="*" />
    </xs:restriction>
  </xs:simpleType>

  <!-- AccessType -->
  <xs:simpleType name="AccessType">
    <xs:restriction base="xs:string">
      <xs:pattern value="[rwxp]+" />
    </xs:restriction>
  </xs:simpleType>

  <!-- Security Type Enumeration -->
  <xs:simpleType name="SecurityTypeEnum">
    <xs:restriction base="xs:token">
      <xs:enumeration value="" />
      <xs:enumeration value="c"/>
      <xs:enumeration value="s"/>
      <xs:enumeration value="n"/>
    </xs:restriction>
  </xs:simpleType>

  <!-- Privilege Type Enumeration -->
  <xs:simpleType name="PrivilegeTypeEnum">
    <xs:restriction base="xs:token">
      <xs:enumeration value=""/>
      <xs:enumeration value="u"/>
      <xs:enumeration value="p"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="PhysicalTypeEnum">
    <xs:restriction base="xs:token">
      <xs:enumeration value="RAM"/>
      <xs:enumeration value="ROM"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="MpcTypeEnum">
    <xs:restriction base="xs:token">
      <xs:enumeration value="s"/>
      <xs:enumeration value="p"/>
      <xs:enumeration value="sp"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="SlotTypeEnum">
    <xs:restriction base="xs:token">
      <xs:enumeration value="s"/>
      <xs:enumeration value="p"/>
      <xs:enumeration value="sp"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="DeviceType">
    <xs:choice maxOccurs="3">
      <xs:element name="package" minOccurs="0" maxOccurs="1">
        <xs:complexType>
          <xs:attribute name="vendor" type="xs:string"       use="required" />
          <xs:attribute name="name"   type="xs:string"       use="required" />
          <xs:attribute name="info"    type="xs:string"       use="optional" />
          <xs:attribute name="url"     type="xs:anyURI"       use="optional" />
          <xs:attribute name="version" type="PackVersionType" use="optional" />
        </xs:complexType>
      </xs:element>
      <xs:element name="processor" maxOccurs="unbounded">
        <xs:complexType>
          <!-- Pname defines an identifier for a specific processor in a multi-processor devices -->
          <xs:attribute name="Pname"          type="RestrictedString"   use="optional"/>
          <!-- Punits specifies the number of processing units in a symmetric multi-processor core -->
          <xs:attribute name="Punits"         type="InstancesType"      use="optional" />
          <!-- Dcore specifies the processor from a list of supported processors -->
          <xs:attribute name="Dcore"          type="DcoreType"          use="required"/>
          <!-- Dfpu specifies the hardware floating point unit -->
          <xs:attribute name="Dfpu"           type="DfpuTypeEnum"       use="required"/>
          <!-- Dmpu specifies the memory protection unit -->
          <xs:attribute name="Dmpu"           type="DmpuTypeEnum"       use="required"/>
          <!-- Dtz specifies the processor TrustZone support -->
          <xs:attribute name="Dtz"            type="DtzTypeEnum"        use="optional"/>
          <!-- Tdsp specifies the processor support for DSP instructions -->
          <xs:attribute name="Ddsp"           type="DdspTypeEnum"       use="required"/>
          <!-- Dendian specifies the endianess supported by the processor -->
          <xs:attribute name="Dendian"        type="DendianTypeEnum"    use="required"/>
          <!-- Dclock specifies the maximum core clock frequency -->
          <xs:attribute name="Dclock"         type="xs:unsignedInt"     use="required"/>
          <!-- DcoreVersion specifies the revision of the processor -->
          <xs:attribute name="DcoreVersion"   type="DcoreVersionType"   use="required"/>
          <xs:attribute name="DnumInterrupts" type="NonNegativeInteger" use="optional"/>
          <xs:attribute name="DnumMpuRegions" type="NonNegativeInteger" use="optional"/>
          <xs:attribute name="DnumSauRegions" type="NonNegativeInteger" use="optional"/>
          <!-- info brief description -->
          <xs:attribute name="info"           type="xs:string"          use="optional"/>
        </xs:complexType>
      </xs:element>
    </xs:choice>
    <xs:attribute name="Dvendor" type="xs:string"        use="required"/>
    <xs:attribute name="Dname"   type="RestrictedString" use="required"/>
    <xs:attribute name="info"    type="xs:string"        use="optional"/>
  </xs:complexType>

  <xs:complexType name="InterruptType">
    <xs:attribute name="name"     type="xs:string"          use="required"/>
    <xs:attribute name="irqn"    type="Integer" use="required"/>
    <xs:attribute name="info"     type="xs:string"/>
    <xs:attribute name="security" type="SecurityTypeEnum"/>
  </xs:complexType>

  <xs:complexType name="SlotType">
    <xs:choice maxOccurs="unbounded" minOccurs="0">
      <xs:element name="slot" type="SlotType"/>
      <xs:element name="interrupt" type="InterruptType"/>
      <xs:element name="setup" type="SetupType"/>
    </xs:choice>
    <xs:attribute name="name"       type="xs:string"/>
    <xs:attribute name="secure"     type="xs:boolean" default="false"/>
    <xs:attribute name="privilege"  type="xs:boolean" default="false"/>
  </xs:complexType>

  <xs:complexType name="PeripheralType">
    <xs:choice maxOccurs="unbounded" minOccurs="0">
      <xs:element name="slot"      type="SlotType"/>
      <xs:element name="interrupt" type="InterruptType"/>
      <xs:element name="setup"     type="SetupType"/>
    </xs:choice>
    <xs:attribute name="name"      type="xs:string"          use="required"/>
    <xs:attribute name="start"     type="NonNegativeInteger" use="optional"/>
    <xs:attribute name="start_ns"  type="NonNegativeInteger" use="optional"/>
    <xs:attribute name="start_s"   type="NonNegativeInteger" use="optional"/>
    <xs:attribute name="physical"  type="NonNegativeInteger" use="optional"/>
    <xs:attribute name="offset"    type="NonNegativeInteger" use="optional"/>
    <xs:attribute name="size"      type="NonNegativeInteger" use="required"/>
    <xs:attribute name="shared"    type="xs:boolean"         use="optional"/>
    <xs:attribute name="dma"       type="xs:boolean"         use="optional"/>
    <xs:attribute name="external"  type="xs:boolean"         use="optional"/>
    <xs:attribute name="Pname"     type="xs:string"          use="optional"/>
    <xs:attribute name="access"    type="AccessType"         use="optional"/>
    <xs:attribute name="security"  type="SecurityTypeEnum"   use="optional"/>
    <xs:attribute name="privilege" type="PrivilegeTypeEnum"  use="optional"/>
    <xs:attribute name="info"      type="xs:string"          use="optional"/>
    <xs:attribute name="slot_name" type="xs:string"          use="optional"/>
    <xs:attribute name="slot_type" type="SlotTypeEnum"       use="optional"/>
  </xs:complexType>

  <xs:complexType name="SauInitType">
    <xs:all>
      <xs:element name="region">
        <xs:complexType>
        <xs:attribute name="Pname"    type="xs:string"          use="optional"/>
        <xs:attribute name="start"    type="NonNegativeInteger" use="required"/>
        <xs:attribute name="size"     type="NonNegativeInteger" use="required"/>
        <xs:attribute name="security" type="SecurityTypeEnum"   use="optional"/>
        <xs:attribute name="info"     type="xs:string"          use="optional"/>
        </xs:complexType>
      </xs:element>
    </xs:all>
  </xs:complexType>

  <xs:complexType name="SetupType">
    <xs:attribute name="name"      type="xs:string"          use="required"/>
    <xs:attribute name="index"     type="NonNegativeInteger" use="optional"/>
    <xs:attribute name="value"     type="NonNegativeInteger" use="required"/>
    <xs:attribute name="security"  type="SecurityTypeEnum"   use="optional"/>
    <xs:attribute name="privilege" type="PrivilegeTypeEnum"  use="optional"/>
    <xs:attribute name="info"      type="xs:string"          use="optional"/>
  </xs:complexType>

  <xs:complexType name="ResourcesType">
    <xs:all>
      <xs:element name="sau_init" type="SauInitType" minOccurs="0" maxOccurs="1"/>
      <xs:element name="memories" minOccurs="0" maxOccurs="1">
        <xs:complexType>
          <xs:choice maxOccurs="unbounded">
            <xs:element name="mpc" minOccurs="0" maxOccurs="unbounded">
              <xs:complexType>
                <xs:attribute name="name"      type="xs:string"          use="required"/>
                <xs:attribute name="start"     type="NonNegativeInteger" use="required"/>
                <xs:attribute name="size"      type="NonNegativeInteger" use="required"/>
                <xs:attribute name="blk_size"  type="NonNegativeInteger" use="required"/>
                <xs:attribute name="type"      type="MpcTypeEnum"        use="optional"/>
                <xs:attribute name="info"      type="xs:string"          use ="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="memory"             minOccurs="0" maxOccurs="unbounded">
              <xs:complexType>
                <xs:attribute name="parent"    type="xs:string"          use="optional"/>
                <xs:attribute name="name"      type="xs:string"          use="required"/>
                <xs:attribute name="type"      type="PhysicalTypeEnum"   use="optional"/>
                <xs:attribute name="start"     type="NonNegativeInteger" use="required"/>
                <xs:attribute name="physical"  type="NonNegativeInteger" use="optional"/>
                <xs:attribute name="size"      type="NonNegativeInteger" use="required"/>
                <xs:attribute name="access"    type="AccessType"         use="optional"/>
                <xs:attribute name="security"  type="SecurityTypeEnum"   use="optional"/>
                <xs:attribute name="privilege" type="PrivilegeTypeEnum"  use="optional"/>
                <xs:attribute name="startup"   type="xs:boolean"         use="optional"/>
                <xs:attribute name="uninit"    type="xs:boolean"         use="optional"/>
                <xs:attribute name="shared"    type="xs:boolean"         use="optional"/>
                <xs:attribute name="dma"       type="xs:boolean"         use="optional"/>
                <xs:attribute name="external"  type="xs:boolean"         use="optional"/>
                <xs:attribute name="Pname"     type="xs:string"          use="optional"/>
                <xs:attribute name="info"      type="xs:string"          use="optional"/>
                <xs:attribute name="linker_control"  type="xs:string"          use="optional"/>
              </xs:complexType>
            </xs:element>
          </xs:choice>
        </xs:complexType>
      </xs:element>
      <xs:element name="peripherals" minOccurs="0">
        <xs:complexType>
          <xs:choice maxOccurs="unbounded">
            <xs:element name="group">
              <xs:complexType>
                <xs:choice maxOccurs="unbounded">
                  <xs:element name="peripheral" type="PeripheralType" maxOccurs="unbounded"/>
                  <xs:element name="setup"      type="SetupType"      minOccurs="0"/>
                </xs:choice>
                <xs:attribute name="name"      type="xs:string"          use="required"/>
                <xs:attribute name="start"     type="NonNegativeInteger" use="optional"/>
                <xs:attribute name="start_s"   type="NonNegativeInteger" use="optional"/>
                <xs:attribute name="start_ns"  type="NonNegativeInteger" use="optional"/>
                <xs:attribute name="physical"  type="NonNegativeInteger" use="optional"/>
                <xs:attribute name="offset"    type="NonNegativeInteger" use="optional"/>
                <xs:attribute name="size"      type="NonNegativeInteger" use="optional"/>
                <xs:attribute name="shared"    type="xs:boolean"         use="optional"/>
                <xs:attribute name="dma"       type="xs:boolean"         use="optional"/>
                <xs:attribute name="external"  type="xs:boolean"         use="optional"/>
                <xs:attribute name="Pname"      type="xs:string"         use="optional"/>
                <xs:attribute name="access"    type="AccessType"         use="optional"/>
                <xs:attribute name="security"  type="SecurityTypeEnum"   use="optional"/>
                <xs:attribute name="privilege" type="PrivilegeTypeEnum"  use="optional"/>
                <xs:attribute name="info"      type="xs:string"          use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="peripheral" type="PeripheralType" minOccurs="0"/>
            <xs:element name="setup"      type="SetupType"      minOccurs="0"/>
          </xs:choice>
        </xs:complexType>
      </xs:element>
    </xs:all>
  </xs:complexType>

  <xs:complexType name="CreatorType">
    <xs:attribute name="tool"       type="xs:string"        use="optional"/>
    <xs:attribute name="rzone"      type="xs:string"        use="optional"/>
    <xs:attribute name="azone"      type="xs:string"        use="optional"/>
    <xs:attribute name="zone"       type="xs:string"        use="optional"/>
    <xs:attribute name="zone_info"  type="xs:string"        use="optional"/>
    <xs:attribute name="security"   type="SecurityTypeEnum" use="optional"/>
  </xs:complexType>

  <!-- description root point -->
  <xs:element name="rzone" nillable="true">
    <xs:complexType>
      <xs:all>
        <xs:element name="creator"      type="CreatorType"   minOccurs="0"/>
        <xs:element name="device"       type="DeviceType"    minOccurs="1"/>
        <xs:element name="resources"    type="ResourcesType" minOccurs="1"/>
      </xs:all>
      <xs:attribute name="schemaVersion" type="SchemaVersionType" use="optional" />
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Hasnaoui-Youssef/trailer_vibes/resources/XML/Rzone/STM32_DIE494_48_320.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<rzone xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" schemaVersion="0.3.1" xsi:noNamespaceSchemaLocation="../../Schemas/RZONE.xsd">

  <device Dname="STM32WB-320K" Dvendor="STMicroelectronics:13" info="ARM Cortex-M4, 48 KB RAM, 320 KB FLASH">
    <package info="STMicroelectronics STM32WB Series Device Support" name="STM32WBxx_DFP" url="http://www.st.com/" vendor="STMicroelectronics" version="0.0.1-dev1"/>
    <processor Dclock="64000000" Dcore="ARM Cortex-M4" DcoreVersion="r0_p1" Ddsp="DSP" Dendian="Little-endian" DnumInterrupts="83"/>
  </device>

  <resources>

    <memories>
      <memory access="rx" info="Flash memory" name="Flash" size="0x00050000" start="0x08000000" type="ROM"/>

      <memory access="rwx" info="SRAM2 Code" name="SRAM2_C" physical="0x20030000" size="0x00009000" start="0x10000000" type="RAM"/>

      <memory access="rwx" info="SRAM1" name="SRAM1" size="0x00003000" start="0x20000000" type="RAM"/>
      <memory access="rwx" info="SRAM2" name="SRAM2" size="0x00009000" start="0x20030000" type="RAM"/>
    </memories>

   </resources>

</rzone>

=== Hasnaoui-Youssef/trailer_vibes/resources/XML/Rzone/STM32_DIE454_256_1024.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<rzone xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" schemaVersion="0.3.1" xsi:noNamespaceSchemaLocation="../../Schemas/RZONE.xsd">

  <device Dname="STM32U3-1M" Dvendor="STMicroelectronics:13" info="ARM Cortex-M33, 256 KB RAM, 1 MB FLASH">
    <package info="STMicroelectronics STM32U3 Series Device Support" name="STM32U3xx_DFP" url="http://www.st.com/" vendor="STMicroelectronics" version="0.0.1-dev1"/>
    <processor Dclock="96000000" Dcore="ARM Cortex-M33" DcoreVersion="r0p4_p1" Ddsp="DSP" Dendian="Little-endian" Dfpu="SP_FPU" Dmpu="MPU" Dtz="TZ" DnumInterrupts="137"  DnumMpuRegions="20" DnumSecMpuRegions="12" DnumSauRegions="8"/>
  </device>

  <resources>

    <sau_init>
      <region start="0x08000000" size="0x04000000" security="n" info="Non-Secure Code"/>
      <region start="0x20000000" size="0x10000000" security="n" info="Non-Secure RAM"/>
      <region start="0x40000000" size="0x10000000" security="n" info="Non-Secure Peripherals"/>
    </sau_init>

    <memories>
      <memory access="rx" info="Flash memory" name="Flash_NS" security="n" size="0x00100000" start="0x08000000" type="ROM"/>
      <memory access="rwx" info="SRAM Code" name="RAM_C_NS" physical="0x20000000" security="n" size="0x00040000" start="0x0A000000" type="RAM"/>

      <memory access="rx" info="Flash memory" name="Flash_S" physical="0x08000000" security="c" size="0x00100000" start="0x0C000000" type="ROM"/>
      <memory access="rwx" info="SRAM Code" name="RAM_C_S" physical="0x20000000" security="c" size="0x00040000" start="0x0E000000" type="RAM"/>

      <memory access="rwx" info="SRAM" name="SRAM_NS" security="n" size="0x00040000" start="0x20000000" type="RAM"/>

      <memory access="rwx" info="SRAM" name="SRAM_S" physical="0x20000000" security="c" size="0x00040000" start="0x30000000" type="RAM"/>

      <mpc blk_size="0x200" sblk_size="0x20" info="SRAM1" name="GTZC1_MPCBB1" size="0x00030000" start="0x20000000" type="sp"/>
      <mpc blk_size="0x200" sblk_size="0x20" info="SRAM2" name="GTZC1_MPCBB2" size="0x00010000" start="0x20030000" type="sp"/>

      <mpc blk_size="0x2000" info="Flash Bank1" name="FLASH_BB1" size="0x00080000" start="0x08000000" type="sp"/>
      <mpc blk_size="0x2000" info="Flash Bank2" name="FLASH_BB2" size="0x00080000" start="0x08080000" type="sp"/>

      <mpcwm sections="2" granularity="0x00020000" info="OctoSPI1" name="GTZC1_MPCWM1" size="0x10000000" start="0x90000000" type="sp"/>

      <mpcwm sections="1" granularity="0x00002000" info="Flash Bank1" name="FLASH_WM1" size="0x00080000" start="0x08000000" type="s"/>
      <mpcwm sections="1" granularity="0x00002000" info="Flash Bank2" name="FLASH_WM2" size="0x00080000" start="0x08080000" type="s"/>
    </memories>

   </resources>

</rzone>

=== Hasnaoui-Youssef/trailer_vibes/resources/XML/Rzone/STM32_DIE032_64_512.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<rzone xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" schemaVersion="0.3.1" xsi:noNamespaceSchemaLocation="../../Schemas/RZONE.xsd">

  <device Dname="STM32WB0-512K" Dvendor="STMicroelectronics:13" info="ARM Cortex-M0+, 64 KB RAM, 512 KB FLASH">
    <package info="STMicroelectronics STM32WB0 Series Device Support" name="STM32WB0xx_DFP" url="http://www.st.com/" vendor="STMicroelectronics" version="0.0.1-dev1"/>
    <processor Dclock="64000000" Dcore="ARM Cortex-M0+" DcoreVersion="r0_p1" Ddsp="DSP" Dendian="Little-endian" DnumInterrupts="83" DnumMpuRegions="8" SubRegions="8"/>
  </device>

  <resources>

    <memories>
      <memory access="rx" info="ROM memory" name="REGION_ROM" size="0x00001800" start="0x10000000" type="ROM"/>
      <memory access="rx" info="Flash memory" name="Flash" size="0x00080000" start="0x10040000" type="ROM"/>

      <memory access="rwx" info="SRAM0" name="SRAM0" size="0x00004000" start="0x20000000" type="RAM"/>
      <memory access="rwx" info="SRAM1" name="SRAM1" size="0x00004000" start="0x20004000" type="RAM"/>
      <memory access="rwx" info="SRAM2" name="SRAM2" size="0x00004000" start="0x20008000" type="RAM"/>
      <memory access="rwx" info="SRAM3" name="SRAM3" size="0x00004000" start="0x2000C000" type="RAM"/>
    </memories>

   </resources>

</rzone>

=== Hasnaoui-Youssef/trailer_vibes/resources/XML/Rzone/STM32_DIE4B0_512_2048.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<rzone xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" schemaVersion="0.3.1" xsi:noNamespaceSchemaLocation="../../Schemas/RZONE.xsd">

  <device Dname="STM32WBA-2M" Dvendor="STMicroelectronics:13" info="ARM Cortex-M33, 512 KB RAM, 2 MB FLASH">
    <package info="STMicroelectronics STM32WBA Series Device Support" name="STM32WBAxx_DFP" url="http://www.st.com/" vendor="STMicroelectronics" version="0.0.1-dev1"/>
    <processor Dclock="10000000" Dcore="ARM Cortex-M33" DcoreVersion="r0p4_p1" Ddsp="DSP" Dendian="Little-endian" Dfpu="SP_FPU" Dmpu="MPU" Dtz="TZ" DnumInterrupts="82"  DnumMpuRegions="16" DnumSecMpuRegions="8" DnumSauRegions="8"/>
  </device>

  <resources>

    <sau_init>
      <region start="0x08000000" size="0x04000000" security="n" info="Non-Secure Code"/>
      <region start="0x0BF80000" size="0x00038000" security="n" info="Non-Secure System Flash"/>
      <region start="0x20000000" size="0x10000000" security="n" info="Non-Secure RAM"/>
      <region start="0x40000000" size="0x10000000" security="n" info="Non-Secure Peripherals"/>
    </sau_init>

    <memories>
      <memory access="rx" info="Flash memory" name="Flash_NS" security="n" size="0x00200000" start="0x08000000" type="ROM"/>

      <memory access="rx" info="Flash memory" name="Flash_S" physical="0x08000000" security="c" size="0x00200000" start="0x0C000000" type="ROM"/>

      <memory access="rwx" info="SRAM1" name="SRAM1_NS" security="n" size="0x00070000" start="0x20000000" type="RAM"/>
      <memory access="rwx" info="SRAM2" name="SRAM2_NS" security="n" size="0x00010000" start="0x20070000" type="RAM"/>
      <memory access="rwx" info="RX/TX_RAM_Radio" name="RX/TX_RAM_NS" security="n" size="0x00004000" start="0x48028000" type="RAM"/>

      <memory access="rwx" info="SRAM1" name="SRAM1_S" physical="0x20000000" security="c" size="0x00070000" start="0x30000000" type="RAM"/>
      <memory access="rwx" info="SRAM2" name="SRAM2_S" physical="0x20070000" security="c" size="0x00010000" start="0x30070000" type="RAM"/>
      <memory access="rwx" info="RX/TX_RAM_Radio" name="RX/TX_RAM_S" physical="0x48028000" security="c" size="0x00004000" start="0x58028000" type="RAM"/>

      <mpc blk_size="0x200" sblk_size="0x20" info="SRAM1" name="GTZC1_MPCBB1" size="0x00070000" start="0x20000000" type="sp"/>
      <mpc blk_size="0x200" sblk_size="0x20" info="SRAM2" name="GTZC1_MPCBB2" size="0x00010000" start="0x20070000" type="sp"/>
      <mpc blk_size="0x200" sblk_size="0x20" info="RX/TX_RAM_Radio" name="GTZC1_MPCBB6" size="0x00004000" start="0x48028000" type="sp"/>

      <mpc blk_size="0x2000" info="Flash Bank1" name="FLASH_BB1" size="0x00100000" start="0x08000000" type="sp"/>
      <mpc blk_size="0x2000" info="Flash Bank2" name="FLASH_BB2" size="0x00100000" start="0x08100000" type="sp"/>

      <mpcwm sections="1" granularity="0x00002000" info="Flash Bank1" name="FLASH_WM1" size="0x00100000" start="0x08000000" type="s"/>
      <mpcwm sections="1" granularity="0x00002000" info="Flash Bank2" name="FLASH_WM2" size="0x00100000" start="0x08100000" type="s"/>
    </memories>

   </resources>

</rzone>
