=== Hasnaoui-Youssef/trailer_vibes/resources/Schemas/RZONE.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--

  Copyright (c) 2020 ARM Limited. All rights reserved.

  SPDX-License-Identifier: Apache-2.0

  Licensed under the Apache License, Version 2.0 (the License); you may
  not use this file except in compliance with the License.
  You may obtain a copy of the License at

  www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an AS IS BASIS, WITHOUT
  WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.

  $Date:        14. April 2020
  $Revision:    0.3.1

  $Project: Schema File for CMSIS-Zone resource description file *.rzone
  Version History:

  0.0.1: Initial Version
  0.0.2: splitting resources and assignments into separate files
         - resources only
  0.1.0: adding security attribute for memory, peripheral and assign
  0.1.1: adding privilege attribute for memory, peripheral and assign tags
  0.2.0: adding sau_init, mpc, peripheral setup element for security and privilege control
  0.3.0: rename Pref to Pname, removed processor_group element, added peripheral childs interrupt, setup and slot elements
  0.3.1: added DnumMpuRegions to rzone/device/processor element with default value 8
-->

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="qualified" version="0.1.1">

  <!-- NonNegativeInteger specifies the format in which numbers are represented in hexadecimal or decimal format -->
  <xs:simpleType name="NonNegativeInteger">
    <xs:restriction base="xs:string">
      <xs:pattern value="[+]?(0x|0X)?[0-9a-fA-F]+" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="Integer">
    <xs:restriction base="xs:string">
      <xs:pattern value="[+\-]?(0x|0X)?[0-9a-fA-F]+" />
    </xs:restriction>
  </xs:simpleType>

  <!-- some strings are used to construct filenames (e.g. package name). Such names can contain only subset of characters
       and must not contain neither spaces nor dots.  -->
  <xs:simpleType name="RestrictedString">
    <xs:restriction base="xs:string">
      <xs:pattern value="[\-_A-Za-z0-9]+" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="SchemaVersionType">
    <xs:restriction base="xs:string">
      <xs:pattern value="[0-9]+\.[0-9]+((\.[0-9]+)|())" />
    </xs:restriction>
  </xs:simpleType>

  <!-- semantic versioning -->
  <xs:simpleType name="PackVersionType">
    <xs:restriction base="xs:string">
      <!-- major . minor . patch [[-]quality] [+build] -->
      <xs:pattern value="[0-9]+.[0-9]+.[0-9]+((\-[0-9A-Za-z_\-\.]+)|([_A-Za-z][0-9A-Za-z_\-\.]*)|())((\+[\-\._A-Za-z0-9]+)|())" />
    </xs:restriction>
  </xs:simpleType>

  <!-- CoreRevisionType specifies the CPU revision format as defined by ARM (rNpM) -->
  <xs:simpleType name="DcoreVersionType">
    <xs:restriction base="xs:string">
      <xs:pattern value="r[0-9]*p[0-9]*"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="InstancesType">
    <xs:restriction base="xs:unsignedInt">
      <xs:minInclusive value="1" />
    </xs:restriction>
  </xs:simpleType>

  <!-- Dcore enumeration type -->
  <xs:simpleType name="DcoreType">
    <xs:restriction base="xs:string">
      <xs:pattern value="SC[0-9][0-9][0-9]" />
      <xs:pattern value="Cortex\-[AMR][0-9][0-9]?[P]?" />
    </xs:restriction>
  </xs:simpleType>


  <!-- Dfpu enumeration type -->
  <xs:simpleType name="DfpuTypeEnum">
    <xs:restriction base="xs:token">
      <!-- core has FPU (type of FPU depends on Dcore) -->
      <xs:enumeration value="FPU" />
      <xs:enumeration value="1" />
      <!-- core has no FPU -->
      <xs:enumeration value="NO_FPU" />
      <xs:enumeration value="0" />
      <!-- single precision FPU -->
      <xs:enumeration value="SP_FPU" />
      <!-- double precision FPU -->
      <xs:enumeration value="DP_FPU" />
      <!-- any -->
    </xs:restriction>
  </xs:simpleType>

  <!-- Dmpu enumeration type -->
  <xs:simpleType name="DmpuTypeEnum">
    <xs:restriction base="xs:token">
      <xs:enumeration value="MPU" />
      <xs:enumeration value="NO_MPU" />
      <xs:enumeration value="0" />
      <xs:enumeration value="1" />
      <xs:enumeration value="*" />
    </xs:restriction>
  </xs:simpleType>

  <!-- Dtz TrustZone enumeration type -->
  <xs:simpleType name="DtzTypeEnum">
    <xs:restriction base="xs:token">
      <xs:enumeration value="TZ" />
      <xs:enumeration value="NO_TZ" />
      <xs:enumeration value="1" />
      <xs:enumeration value="0" />
      <xs:enumeration value="*" />
    </xs:restriction>
  </xs:simpleType>

  <!-- Dsecure enumeration type -->
  <xs:simpleType name="DsecureTypeEnum">
    <xs:restriction base="xs:token">
      <xs:enumeration value="Secure" />
      <xs:enumeration value="Non-secure" />
      <xs:enumeration value="1" />
      <xs:enumeration value="0"/>
      <xs:enumeration value="*" />
    </xs:restriction>
  </xs:simpleType>

  <!-- Ddsp DSP extensions enumeration type -->
  <xs:simpleType name="DdspTypeEnum">
    <xs:restriction base="xs:token">
      <xs:enumeration value="DSP" />
      <xs:enumeration value="NO_DSP" />
      <xs:enumeration value="1" />
      <xs:enumeration value="0" />
      <xs:enumeration value="*" />
    </xs:restriction>
  </xs:simpleType>

  <!-- Dendian enumeration type -->
  <xs:simpleType name="DendianTypeEnum">
    <xs:restriction base="xs:token">
      <xs:enumeration value="Little-endian" />
      <xs:enumeration value="Big-endian" />
      <xs:enumeration value="Configurable" />
      <xs:enumeration value="*" />
    </xs:restriction>
  </xs:simpleType>

  <!-- AccessType -->
  <xs:simpleType name="AccessType">
    <xs:restriction base="xs:string">
      <xs:pattern value="[rwxp]+" />
    </xs:restriction>
  </xs:simpleType>

  <!-- Security Type Enumeration -->
  <xs:simpleType name="SecurityTypeEnum">
    <xs:restriction base="xs:token">
      <xs:enumeration value="" />
      <xs:enumeration value="c"/>
      <xs:enumeration value="s"/>
      <xs:enumeration value="n"/>
    </xs:restriction>
  </xs:simpleType>

  <!-- Privilege Type Enumeration -->
  <xs:simpleType name="PrivilegeTypeEnum">
    <xs:restriction base="xs:token">
      <xs:enumeration value=""/>
      <xs:enumeration value="u"/>
      <xs:enumeration value="p"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="PhysicalTypeEnum">
    <xs:restriction base="xs:token">
      <xs:enumeration value="RAM"/>
      <xs:enumeration value="ROM"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="MpcTypeEnum">
    <xs:restriction base="xs:token">
      <xs:enumeration value="s"/>
      <xs:enumeration value="p"/>
      <xs:enumeration value="sp"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="SlotTypeEnum">
    <xs:restriction base="xs:token">
      <xs:enumeration value="s"/>
      <xs:enumeration value="p"/>
      <xs:enumeration value="sp"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="DeviceType">
    <xs:choice maxOccurs="3">
      <xs:element name="package" minOccurs="0" maxOccurs="1">
        <xs:complexType>
          <xs:attribute name="vendor" type="xs:string"       use="required" />
          <xs:attribute name="name"   type="xs:string"       use="required" />
          <xs:attribute name="info"    type="xs:string"       use="optional" />
          <xs:attribute name="url"     type="xs:anyURI"       use="optional" />
          <xs:attribute name="version" type="PackVersionType" use="optional" />
        </xs:complexType>
      </xs:element>
      <xs:element name="processor" maxOccurs="unbounded">
        <xs:complexType>
          <!-- Pname defines an identifier for a specific processor in a multi-processor devices -->
          <xs:attribute name="Pname"          type="RestrictedString"   use="optional"/>
          <!-- Punits specifies the number of processing units in a symmetric multi-processor core -->
          <xs:attribute name="Punits"         type="InstancesType"      use="optional" />
          <!-- Dcore specifies the processor from a list of supported processors -->
          <xs:attribute name="Dcore"          type="DcoreType"          use="required"/>
          <!-- Dfpu specifies the hardware floating point unit -->
          <xs:attribute name="Dfpu"           type="DfpuTypeEnum"       use="required"/>
          <!-- Dmpu specifies the memory protection unit -->
          <xs:attribute name="Dmpu"           type="DmpuTypeEnum"       use="required"/>
          <!-- Dtz specifies the processor TrustZone support -->
          <xs:attribute name="Dtz"            type="DtzTypeEnum"        use="optional"/>
          <!-- Tdsp specifies the processor support for DSP instructions -->
          <xs:attribute name="Ddsp"           type="DdspTypeEnum"       use="required"/>
          <!-- Dendian specifies the endianess supported by the processor -->
          <xs:attribute name="Dendian"        type="DendianTypeEnum"    use="required"/>
          <!-- Dclock specifies the maximum core clock frequency -->
          <xs:attribute name="Dclock"         type="xs:unsignedInt"     use="required"/>
          <!-- DcoreVersion specifies the revision of the processor -->
          <xs:attribute name="DcoreVersion"   type="DcoreVersionType"   use="required"/>
          <xs:attribute name="DnumInterrupts" type="NonNegativeInteger" use="optional"/>
          <xs:attribute name="DnumMpuRegions" type="NonNegativeInteger" use="optional"/>
          <xs:attribute name="DnumSauRegions" type="NonNegativeInteger" use="optional"/>
          <!-- info brief description -->
          <xs:attribute name="info"           type="xs:string"          use="optional"/>
        </xs:complexType>
      </xs:element>
    </xs:choice>
    <xs:attribute name="Dvendor" type="xs:string"        use="required"/>
    <xs:attribute name="Dname"   type="RestrictedString" use="required"/>
    <xs:attribute name="info"    type="xs:string"        use="optional"/>
  </xs:complexType>

  <xs:complexType name="InterruptType">
    <xs:attribute name="name"     type="xs:string"          use="required"/>
    <xs:attribute name="irqn"    type="Integer" use="required"/>
    <xs:attribute name="info"     type="xs:string"/>
    <xs:attribute name="security" type="SecurityTypeEnum"/>
  </xs:complexType>

  <xs:complexType name="SlotType">
    <xs:choice maxOccurs="unbounded" minOccurs="0">
      <xs:element name="slot" type="SlotType"/>
      <xs:element name="interrupt" type="InterruptType"/>
      <xs:element name="setup" type="SetupType"/>
    </xs:choice>
    <xs:attribute name="name"       type="xs:string"/>
    <xs:attribute name="secure"     type="xs:boolean" default="false"/>
    <xs:attribute name="privilege"  type="xs:boolean" default="false"/>
  </xs:complexType>

  <xs:complexType name="PeripheralType">
    <xs:choice maxOccurs="unbounded" minOccurs="0">
      <xs:element name="slot"      type="SlotType"/>
      <xs:element name="interrupt" type="InterruptType"/>
      <xs:element name="setup"     type="SetupType"/>
    </xs:choice>
    <xs:attribute name="name"      type="xs:string"          use="required"/>
    <xs:attribute name="start"     type="NonNegativeInteger" use="optional"/>
    <xs:attribute name="start_ns"  type="NonNegativeInteger" use="optional"/>
    <xs:attribute name="start_s"   type="NonNegativeInteger" use="optional"/>
    <xs:attribute name="physical"  type="NonNegativeInteger" use="optional"/>
    <xs:attribute name="offset"    type="NonNegativeInteger" use="optional"/>
    <xs:attribute name="size"      type="NonNegativeInteger" use="required"/>
    <xs:attribute name="shared"    type="xs:boolean"         use="optional"/>
    <xs:attribute name="dma"       type="xs:boolean"         use="optional"/>
    <xs:attribute name="external"  type="xs:boolean"         use="optional"/>
    <xs:attribute name="Pname"     type="xs:string"          use="optional"/>
    <xs:attribute name="access"    type="AccessType"         use="optional"/>
    <xs:attribute name="security"  type="SecurityTypeEnum"   use="optional"/>
    <xs:attribute name="privilege" type="PrivilegeTypeEnum"  use="optional"/>
    <xs:attribute name="info"      type="xs:string"          use="optional"/>
    <xs:attribute name="slot_name" type="xs:string"          use="optional"/>
    <xs:attribute name="slot_type" type="SlotTypeEnum"       use="optional"/>
  </xs:complexType>

  <xs:complexType name="SauInitType">
    <xs:all>
      <xs:element name="region">
        <xs:complexType>
        <xs:attribute name="Pname"    type="xs:string"          use="optional"/>
        <xs:attribute name="start"    type="NonNegativeInteger" use="required"/>
        <xs:attribute name="size"     type="NonNegativeInteger" use="required"/>
        <xs:attribute name="security" type="SecurityTypeEnum"   use="optional"/>
        <xs:attribute name="info"     type="xs:string"          use="optional"/>
        </xs:complexType>
      </xs:element>
    </xs:all>
  </xs:complexType>

  <xs:complexType name="SetupType">
    <xs:attribute name="name"      type="xs:string"          use="required"/>
    <xs:attribute name="index"     type="NonNegativeInteger" use="optional"/>
    <xs:attribute name="value"     type="NonNegativeInteger" use="required"/>
    <xs:attribute name="security"  type="SecurityTypeEnum"   use="optional"/>
    <xs:attribute name="privilege" type="PrivilegeTypeEnum"  use="optional"/>
    <xs:attribute name="info"      type="xs:string"          use="optional"/>
  </xs:complexType>

  <xs:complexType name="ResourcesType">
    <xs:all>
      <xs:element name="sau_init" type="SauInitType" minOccurs="0" maxOccurs="1"/>
      <xs:element name="memories" minOccurs="0" maxOccurs="1">
        <xs:complexType>
          <xs:choice maxOccurs="unbounded">
            <xs:element name="mpc" minOccurs="0" maxOccurs="unbounded">
              <xs:complexType>
                <xs:attribute name="name"      type="xs:string"          use="required"/>
                <xs:attribute name="start"     type="NonNegativeInteger" use="required"/>
                <xs:attribute name="size"      type="NonNegativeInteger" use="required"/>
                <xs:attribute name="blk_size"  type="NonNegativeInteger" use="required"/>
                <xs:attribute name="type"      type="MpcTypeEnum"        use="optional"/>
                <xs:attribute name="info"      type="xs:string"          use ="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="memory"             minOccurs="0" maxOccurs="unbounded">
              <xs:complexType>
                <xs:attribute name="parent"    type="xs:string"          use="optional"/>
                <xs:attribute name="name"      type="xs:string"          use="required"/>
                <xs:attribute name="type"      type="PhysicalTypeEnum"   use="optional"/>
                <xs:attribute name="start"     type="NonNegativeInteger" use="required"/>
                <xs:attribute name="physical"  type="NonNegativeInteger" use="optional"/>
                <xs:attribute name="size"      type="NonNegativeInteger" use="required"/>
                <xs:attribute name="access"    type="AccessType"         use="optional"/>
                <xs:attribute name="security"  type="SecurityTypeEnum"   use="optional"/>
                <xs:attribute name="privilege" type="PrivilegeTypeEnum"  use="optional"/>
                <xs:attribute name="startup"   type="xs:boolean"         use="optional"/>
                <xs:attribute name="uninit"    type="xs:boolean"         use="optional"/>
                <xs:attribute name="shared"    type="xs:boolean"         use="optional"/>
                <xs:attribute name="dma"       type="xs:boolean"         use="optional"/>
                <xs:attribute name="external"  type="xs:boolean"         use="optional"/>
                <xs:attribute name="Pname"     type="xs:string"          use="optional"/>
                <xs:attribute name="info"      type="xs:string"          use="optional"/>
                <xs:attribute name="linker_control"  type="xs:string"          use="optional"/>
              </xs:complexType>
            </xs:element>
          </xs:choice>
        </xs:complexType>
      </xs:element>
      <xs:element name="peripherals" minOccurs="0">
        <xs:complexType>
          <xs:choice maxOccurs="unbounded">
            <xs:element name="group">
              <xs:complexType>
                <xs:choice maxOccurs="unbounded">
                  <xs:element name="peripheral" type="PeripheralType" maxOccurs="unbounded"/>
                  <xs:element name="setup"      type="SetupType"      minOccurs="0"/>
                </xs:choice>
                <xs:attribute name="name"      type="xs:string"          use="required"/>
                <xs:attribute name="start"     type="NonNegativeInteger" use="optional"/>
                <xs:attribute name="start_s"   type="NonNegativeInteger" use="optional"/>
                <xs:attribute name="start_ns"  type="NonNegativeInteger" use="optional"/>
                <xs:attribute name="physical"  type="NonNegativeInteger" use="optional"/>
                <xs:attribute name="offset"    type="NonNegativeInteger" use="optional"/>
                <xs:attribute name="size"      type="NonNegativeInteger" use="optional"/>
                <xs:attribute name="shared"    type="xs:boolean"         use="optional"/>
                <xs:attribute name="dma"       type="xs:boolean"         use="optional"/>
                <xs:attribute name="external"  type="xs:boolean"         use="optional"/>
                <xs:attribute name="Pname"      type="xs:string"         use="optional"/>
                <xs:attribute name="access"    type="AccessType"         use="optional"/>
                <xs:attribute name="security"  type="SecurityTypeEnum"   use="optional"/>
                <xs:attribute name="privilege" type="PrivilegeTypeEnum"  use="optional"/>
                <xs:attribute name="info"      type="xs:string"          use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="peripheral" type="PeripheralType" minOccurs="0"/>
            <xs:element name="setup"      type="SetupType"      minOccurs="0"/>
          </xs:choice>
        </xs:complexType>
      </xs:element>
    </xs:all>
  </xs:complexType>

  <xs:complexType name="CreatorType">
    <xs:attribute name="tool"       type="xs:string"        use="optional"/>
    <xs:attribute name="rzone"      type="xs:string"        use="optional"/>
    <xs:attribute name="azone"      type="xs:string"        use="optional"/>
    <xs:attribute name="zone"       type="xs:string"        use="optional"/>
    <xs:attribute name="zone_info"  type="xs:string"        use="optional"/>
    <xs:attribute name="security"   type="SecurityTypeEnum" use="optional"/>
  </xs:complexType>

  <!-- description root point -->
  <xs:element name="rzone" nillable="true">
    <xs:complexType>
      <xs:all>
        <xs:element name="creator"      type="CreatorType"   minOccurs="0"/>
        <xs:element name="device"       type="DeviceType"    minOccurs="1"/>
        <xs:element name="resources"    type="ResourcesType" minOccurs="1"/>
      </xs:all>
      <xs:attribute name="schemaVersion" type="SchemaVersionType" use="optional" />
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Hasnaoui-Youssef/trailer_vibes/resources/XML/Rzone/STM32_DIE450_864_2048_DUAL.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<rzone xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" schemaVersion="0.3.1" xsi:noNamespaceSchemaLocation="../../Schemas/RZONE.xsd">

  <device Dname="STM32H7-2M" Dvendor="STMicroelectronics:13" info="ARM Cortex-M7, 1 MB RAM, 2 MB FLASH">
    <package info="STMicroelectronics STM32H7 Series Device Support" name="STM32H7xx_DFP" url="http://www.st.com/" vendor="STMicroelectronics" version="0.0.1-dev1"/>
    <processor Dclock="480000000" Dcore="ARM Cortex-M7" DcoreVersion="r1p1" Ddsp="DSP" Dendian="Little-endian" Dfpu="DP_FPU" Dmpu="MPU" DnumInterrupts="149"  DnumMpuRegions="16" SubRegions="8" Pname="CM7"/>
    <processor Dclock="240000000" Dcore="ARM Cortex-M4" DcoreVersion="r0p1" Ddsp="DSP" Dendian="Little-endian" Dfpu="SP_FPU" Dmpu="MPU" DnumInterrupts="149"  DnumMpuRegions="8" SubRegions="8" Pname="CM4"/>
  </device>

  <resources>

    <memories>
      <memory access="rwx" info="ITCM memory" name="RAM_ITCM" size="0x00010000" start="0x00000000" type="RAM" Pname="CM7"/>
      <memory access="rx" info="Flash memory Bank1" name="Flash Bank1" size="0x00100000" start="0x08000000" type="ROM"/>
      <memory access="rx" info="Flash memory Bank2" name="Flash Bank2" size="0x00100000" start="0x08100000" type="ROM"/>
      <memory access="rwx" info="AHB SRAM1 Code" name="RAM1_AHB_C" size="0x00020000" start="0x10000000" type="RAM"/>
      <memory access="rwx" info="AHB SRAM2 Code" name="RAM2_AHB_C" size="0x00020000" start="0x10020000" type="RAM"/>
      <memory access="rwx" info="AHB SRAM3 Code" name="RAM3_AHB_C" size="0x00008000" start="0x10040000" type="RAM"/>

      <memory access="rwx" info="DTCM memory" name="RAM_DTCM" size="0x00020000" start="0x20000000" type="RAM" Pname="CM7" notification="Not accessible by DMA"/>
      <memory access="rwx" info="AXI SRAM" name="RAM_AXI" size="0x00080000" start="0x24000000" type="RAM"/>
      <memory access="rwx" info="AHB SRAM1" name="RAM1_AHB" size="0x00020000" start="0x30000000" type="RAM"/>
      <memory access="rwx" info="AHB SRAM2" name="RAM2_AHB" size="0x00020000" start="0x30020000" type="RAM"/>
      <memory access="rwx" info="AHB SRAM3" name="RAM3_AHB" size="0x00008000" start="0x30040000" type="RAM"/>  
      <memory access="rwx" info="AHB SRAM Domain 4" name="RAM_AHB_D4" size="0x00010000" start="0x38000000" type="RAM"/>       
      <memory access="rwx" info="Backup SRAM" name="BKPSRAM" size="0x00001000" start="0x38800000" type="RAM"/>

      <provisioning info="FMC Bank1" name="FMC NOR Bank1" size="0x10000000" start="0x60000000"/>
      <provisioning info="FMC Bank3" name="FMC NAND Bank3" size="0x10000000" start="0x80000000"/>
      <provisioning info="QuadSPI" name="QuadSPI" size="0x10000000" start="0x90000000"/>

      <provisioning info="FMC SDRAM Bank1" name="FMC SDRAM Bank1" size="0x10000000" start="0xC0000000"/>
      <provisioning info="FMC SDRAM Bank2" name="FMC SDRAM Bank2" size="0x04000000" start="0xD0000000"/>
    </memories>

   </resources>

</rzone>

=== Hasnaoui-Youssef/trailer_vibes/resources/XML/Rzone/STM32_DIE486_4200_0.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<rzone xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" schemaVersion="0.3.1" xsi:noNamespaceSchemaLocation="../../Schemas/RZONE.xsd">

  <device Dname="STM32N6" Dvendor="STMicroelectronics:13" info="ARM Cortex-M55, 4200 KB RAM">
    <package info="STMicroelectronics STM32N6 Series Device Support" name="STM32N6xx_DFP" url="http://www.st.com/" vendor="STMicroelectronics" version="0.0.1-dev1"/>
    <processor Dclock="400000000" Dcore="ARM Cortex-M55" DcoreVersion="r0_p1" Ddsp="DSP" Dendian="Little-endian" DnumInterrupts="208" Dmpu="MPU" DnumMpuRegions="32" DnumSecMpuRegions="16" DnumSauRegions="8"/>
  </device>

  <resources>
    <sau_init>
      <region start="0x08000000" size="0x04000000" security="n" info="Non-Secure Code"/>
      <region start="0x20000000" size="0x10000000" security="n" info="Non-Secure RAM"/>
      <region start="0x40000000" size="0x10000000" security="n" info="Non-Secure Peripherals"/>
    </sau_init>
    <memories>    

	  <memory access="rwx" info="ITCM" security="c" name="ITCM_S" physical="0x00000000" size="0x00010000" start="0x10000000" type="RAM"/>
	  <memory access="rwx" info="DTCM" security="c" name="DTCM_S" physical="0x20000000" size="0x00020000" start="0x30000000" type="RAM"/>
	  <memory access="rwx" info="FLEXRAM" name="FLEXRAM_S" physical="0x24000000" security="c" size="0x00064000" start="0x34000000" type="RAM"/>
	  <memory access="rwx" info="AXI SRAM1" name="SRAM1_S" physical="0x24064000" security="c" size="0x0009C000" start="0x34064000" type="RAM"/>
      <memory access="rwx" info="AXI SRAM2" name="SRAM2_S" physical="0x24100000" security="c" size="0x00100000" start="0x34100000" type="RAM"/>
	  <memory access="rwx" info="AXI SRAM3" name="SRAM3_S" physical="0x24200000" security="c" size="0x00070000" start="0x34200000" type="RAM"/>
      <memory access="rwx" info="AXI SRAM4" name="SRAM4_S" physical="0x24270000" security="c" size="0x00070000" start="0x34270000" type="RAM"/>
	  <memory access="rwx" info="AXI SRAM5" name="SRAM5_S" physical="0x242E0000" security="c" size="0x00070000" start="0x342E0000" type="RAM"/>
      <memory access="rwx" info="AXI SRAM6" name="SRAM6_S" physical="0x24350000" security="c" size="0x00070000" start="0x34350000" type="RAM"/>
      <memory access="rwx" info="CACHEAXI" name="CACHEAXI_S" physical="0x243C0000" security="c" size="0x00040000" start="0x343C0000" type="RAM"/>
      <memory access="rwx" info="VENCRAM" name="VENCRAM_S" physical="0x24400000" security="c" size="0x00020000" start="0x34400000" type="RAM"/>
	  <memory access="rwx" info="AHB_SRAM1" name="AHB_SRAM1_S" physical="0x28000000" security="c" size="0x00004000" start="0x38000000" type="RAM"/>
	  <memory access="rwx" info="AHB_SRAM2" name="AHB_SRAM2_S" physical="0x28004000" security="c" size="0x00004000" start="0x38004000" type="RAM"/>
	  <memory access="rwx" info="Backup SRAM" name="BackUp_SRAM_S" physical="0x2C000000" security="c" size="0x00002000" start="0x3C000000" type="RAM"/>
	  <memory access="rwx" info="ITCM" security="n" name="ITCM_NS" size="0x00010000" start="0x00000000" type="RAM"/>
	  <memory access="rwx" info="DTCM" security="n" name="DTCM_NS" size="0x00020000" start="0x20000000" type="RAM"/>
	  <memory access="rwx" info="FLEXRAM" name="FLEXRAM_NS" security="n" size="0x00064000" start="0x24000000" type="RAM"/>
	  <memory access="rwx" info="AXI SRAM1" name="SRAM1_NS" security="n" size="0x0009C000" start="0x24064000" type="RAM"/>
      <memory access="rwx" info="AXI SRAM2" name="SRAM2_NS" security="n" size="0x00100000" start="0x24100000" type="RAM"/>
	  <memory access="rwx" info="AXI SRAM3" name="SRAM3_NS" security="n" size="0x00070000" start="0x24200000" type="RAM"/>
      <memory access="rwx" info="AXI SRAM4" name="SRAM4_NS" security="n" size="0x00070000" start="0x24270000" type="RAM"/>
	  <memory access="rwx" info="AXI SRAM5" name="SRAM5_NS" security="n" size="0x00070000" start="0x242E0000" type="RAM"/>
      <memory access="rwx" info="AXI SRAM6" name="SRAM6_NS" security="n" size="0x00070000" start="0x24350000" type="RAM"/>
      <memory access="rwx" info="CACHEAXI" name="CACHEAXI_NS" security="n" size="0x00040000" start="0x243C0000" type="RAM"/>
      <memory access="rwx" info="VENCRAM" name="VENCRAM_NS" security="n" size="0x00020000" start="0x24400000" type="RAM"/>
      <memory access="rwx" info="AHB_SRAM1" name="AHB_SRAM1_NS" security="n" size="0x00004000" start="0x28000000" type="RAM"/>
	  <memory access="rwx" info="AHB_SRAM2" name="AHB_SRAM2_NS" security="n" size="0x00004000" start="0x28004000" type="RAM"/>
	  <memory access="rwx" info="Backup SRAM" name="BackUp_SRAM_NS" security="n" size="0x00002000" start="0x2C000000" type="RAM"/>
	  
	  <provisioning info="FMC Bank1" name="FMC_NOR_Bank1" size="0x10000000" start="0x60000000"/>
      <provisioning info="XSPI2" name="XSPI2" size="0x10000000" start="0x70000000"/> 
	  <provisioning info="XSPI3" name="XSPI3" size="0x10000000" start="0x80000000"/>
      <provisioning info="XSPI1" name="XSPI1" size="0x10000000" start="0x90000000"/>

      <provisioning info="FMC SDRAM Bank1" name="FMC_SDRAM_Bank1" size="0x10000000" start="0xC0000000"/>
      <provisioning info="FMC SDRAM Bank2" name="FMC_SDRAM_Bank2" size="0x10000000" start="0xD0000000"/>
    </memories>

   </resources>

</rzone>
